backend:
  name: git-gateway
  branch: master
  commit_messages:
    create: ğŸ“„ - Create {{collection}} â€œ{{slug}}â€
    update: âœï¸ - Update {{collection}} â€œ{{slug}}â€
    delete: ğŸ—‘ - Delete {{collection}} â€œ{{slug}}â€
    uploadMedia: ğŸ—ƒ - Upload â€œ{{path}}â€
    deleteMedia: ğŸ—‘ - Delete â€œ{{path}}â€

media_folder: static/img
public_folder: /img

collections:
  - name: 'companies'
    label: 'Companies'
    folder: 'assets/content/companies'
    create: true
    format: 'json'
    slug: '{{slug}}'
    editor:
      preview: false
    fields:
      - { label: 'Company Name', name: 'title', widget: 'string' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
      - label: 'Link'
        name: 'link'
        widget: 'string'
        description: 'Link to the offending/SW-exclusive Terms of Service.'
  - name: 'settings'
    label: 'Settings'
    files:
      - label: 'Site Meta'
        name: 'meta'
        file: 'assets/content/meta.json'
        format: 'json'
        fields:
          - { label: 'Header', name: 'header', widget: 'markdown' }
          - { label: 'Intro', name: 'intro', widget: 'markdown' }
          - label: 'Sections'
            name: 'sections'
            widget: 'list'
            fields:
              - { label: 'Title', name: 'title', widget: 'string' }
              - { label: 'Content', name: 'content', widget: 'markdown' }
